// <auto-generated />
namespace SharePoint.Authentication.Sample.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class SampleHighTrustCredentials : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SampleHighTrustCredentials));
        
        string IMigrationMetadata.Id
        {
            get { return "201904140702040_SampleHighTrustCredentials"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
